MainProject/ViewModels/RoleAssignViewModel.cs
namespace MainProject.ViewModels
{
    public class RoleAssignViewModel
    {
        public string RoleId { get; set; }
        public string RoleName { get; set; }
        public bool Exist { get; set; }
    }
}

MainProject/ViewModels/RoleViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace MainProject.ViewModels
{
    public class RoleViewModel
    {
        [Required(ErrorMessage = "Rol ismi gereklidir.")]
        [Display(Name = "Rol İsmi")]
        public string Name { get; set; }

        public string Id { get; set; }
    }
}

MainProject/Controllers/MemberController.cs
using MainProject.Enums;
using MainProject.Identity;
using MainProject.Models;
using MainProject.ViewModels;
using Mapster;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace MainProject.Controllers
{
    [Authorize]
    public class MemberController : BaseController
    {
        public MemberController(UserManager<AppIdentityUser> userManager, SignInManager<AppIdentityUser> signInManager, ProjectDbContext dbContext) : base(userManager, signInManager, null, dbContext)
        {
        }

        public IActionResult Index()
        {
            var user = CurrentUser;

            RegisterUserViewModel userViewModel = user.Adapt<RegisterUserViewModel>();

            return View(userViewModel);
        }

        public IActionResult Home()
        {

            var homepagePhotos = _DbContext.HomeSliderPhotos.ToList();
            return View(homepagePhotos);
        }

        public IActionResult ChangePassword()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> ChangePassword(ChangePasswordViewModel changePasswordViewModel)
        {
            if (ModelState.IsValid)
            {
                var user = CurrentUser;

                bool currentPasswordValid = _userManager.CheckPasswordAsync(user, changePasswordViewModel.OldPassword).Result;

                if (currentPasswordValid)
                {
                    var result = _userManager.ChangePasswordAsync(user, changePasswordViewModel.OldPassword, changePasswordViewModel.NewPassword).Result;

                    if (result.Succeeded)
                    {
                        await _userManager.UpdateSecurityStampAsync(user);

                        //giriş-çıkış işlemini şifre değişir değişmez yapmak için
                        await _signInManager.SignOutAsync();
                        await _signInManager.PasswordSignInAsync(user, changePasswordViewModel.NewPassword, true, false);

                        ViewBag.Success = "true";
                    }
                    else
                    {
                        AddModelError(result);
                    }
                }
                else
                {
                    ModelState.AddModelError("", "Geçerli şifre yanlış!");
                }
            }

            return View(changePasswordViewModel);
        }

        public IActionResult UserInfoEdit()
        {
            var user = CurrentUser;

            RegisterUserViewModel userViewModel = user.Adapt<RegisterUserViewModel>();
            ViewBag.Gender = new SelectList(Enum.GetNames(typeof(Gender)));
            return View(userViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> UserInfoEdit(RegisterUserViewModel registerUserViewModel)
        {
            ModelState.Remove("Password");
            ViewBag.Gender = new SelectList(Enum.GetNames(typeof(Gender)));

            if (ModelState.IsValid)
            {
                string phone = _userManager.GetPhoneNumberAsync(CurrentUser).Result;
                if (phone != registerUserViewModel.PhoneNumber)
                {
                    if (_userManager.Users.Any(w => w.PhoneNumber == registerUserViewModel.PhoneNumber))
                    {
                        ModelState.AddModelError("", "Bu telefon numarası başka üye tarafından kullanılmaktadır.");
                        return View(registerUserViewModel);
                    }

                }

                var user = CurrentUser;
                user.UserName = registerUserViewModel.UserName;
                user.Email = registerUserViewModel.Email;
                user.PhoneNumber = registerUserViewModel.PhoneNumber;
                user.BirthDate = registerUserViewModel.BirthDate ?? DateTime.MinValue;
                user.City = registerUserViewModel.City;
                user.Gender = (int)registerUserViewModel.Gender;
                var result = await _userManager.UpdateAsync(user);

                if (result.Succeeded)
                {
                    await _userManager.UpdateSecurityStampAsync(user);

                    //giriş-çıkış işlemini şifre değişir değişmez yapmak için
                    await _signInManager.SignOutAsync();
                    await _signInManager.SignInAsync(user, true);

                    ViewBag.Success = "true";
                }
                else
                {
                    AddModelError(result);
                }
            }

            return View(registerUserViewModel);
        }

        public void Logout()
        {
            _signInManager.SignOutAsync();
        }

        public IActionResult AccessDenied(string ReturnUrl)
        {
            return View();
        }

        [Authorize(Roles = "Editor,Admin")]
        public IActionResult Editor()
        {
            return View();
        }

        [Authorize(Roles = "Manager,Admin")]
        public IActionResult Manager()
        {
            return View();
        }

        [Authorize(Policy = "Kayseripolicy")]
        public IActionResult KayseriPage()
        {
            return View();
        }

        public async Task<IActionResult> ExchangeRedirect()
        {
            var result = User.HasClaim(w => w.Type == "ExpireDateExchange");
            if (!result)
            {
                Claim ExpireDateExchange = new Claim("ExpireDateExchange", DateTime.Now.AddDays(30).Date.ToShortDateString(), ClaimValueTypes.String, "Internal");

                await _userManager.AddClaimAsync(CurrentUser, ExpireDateExchange);
                await _signInManager.SignOutAsync();
                await _signInManager.SignInAsync(CurrentUser, true);
            }

            return RedirectToAction("Exchange");
        }

        [Authorize(Policy = "ExchangePolicy")]
        public IActionResult Exchange()
        {
            return View();
        }
    }
}

MainProject/Views/Admin/Claims.cshtml
@model List<System.Security.Claims.Claim>
@{
    ViewData["Title"] = "Claims";
    Layout = "~/Views/Admin/_AdminLayout.cshtml";
}

<h3>Claims</h3>
<hr />
<table class="table table-bordered table-striped table-responsive">
    <tr>
        <th>Kim</th>
        <th>Dağıtıcı</th>
        <th>Key</th>
        <th>Value</th>

    </tr>

    @foreach (var item in Model)
    {
    <tr>
        <td>@item.Subject.Name</td>
        <td>@item.Issuer</td>
        <td>@item.Type</td>
        <td>@item.Value</td>

    </tr>
    }

</table>

MainProject/Views/Admin/HomePagePhotos.cshtml
@model List<MainProject.Models.HomeSliderPhotos>
@{
    ViewData["Title"] = "Photos";
    Layout = "~/Views/Admin/_AdminLayout.cshtml";
}

<h3>Resimler</h3>
<hr />
    <table class="table table-bordered table-striped">
        <tr>
            <th>Id</th>
            <th>Fotoğraf</th>
            <th>Başlık</th>
            <th>Açıklama</th>
            <th>Eklenme T.</th>
            <th>Silme</th>
        </tr>   
        @foreach (var item in Model)
	{
    <tr>
        <td>@item.PhotoId</td>
        <td><img  width="40" height="40" src= "@String.Format("data:image/gif;base64,{0}", Convert.ToBase64String(item.Photo))" /></td>
        <td>@item.PhotoTitle</td>
        <td>@item.Description</td>
        <td>@item.PhotoAddDate</td>
        <td>
            <form asp-action="DeleteHomeSliderPhoto" asp-route-id="@item.PhotoId" method="post">
                <button class="btn btn-warning" type="submit">Sil</button>
            </form>
        </td>
    </tr>            
	}
        
    </table>
    <a asp-action="HomeSliderPhotoAdd" class="btn btn-outline-info float-sm-right">İlan Foto. Ekle</a>

MainProject/Views/Admin/HomeSliderPhotoAdd.cshtml
@model MainProject.ViewModels.HomeSliderPhotoViewModel

@{
    ViewData["Title"] = "Add Photo";
    Layout = "~/Views/Admin/_AdminLayout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>HomeSliderPhotoAdd</title>
</head>
<body>

    <h4>HomeSliderPhotoViewModel</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="HomeSliderPhotoAdd" method="post" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Photo" class="control-label"></label>
                    <input type="file" id="files" asp-for="Photo" />
                    <span asp-validation-for="Photo" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PhotoTitle" class="control-label"></label>
                    <input asp-for="PhotoTitle" class="form-control" />
                    <span asp-validation-for="PhotoTitle" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <input asp-for="Description" class="form-control" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Ekle" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="HomePagePhotos">Back to List</a>
    </div>

</body>
</html>

MainProject/Views/Admin/Index.cshtml
@model List<AppIdentityUser>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Admin/_AdminLayout.cshtml";
}

<h3>Yönetim Paneli</h3>

MainProject/Views/Admin/RoleAssign.cshtml
@model List<RoleAssignViewModel>
@{
    ViewData["Title"] = "RoleAssign";
    Layout = "~/Views/Admin/_AdminLayout.cshtml";
}

<h3>Yetkilendirme (@ViewBag.userName)</h3>

<form asp-controller="Admin" asp-action="RoleAssign" method="post">
    
    @for (int i = 0; i < Model.Count; i++)
    {
    <div class="form-check">
        <input asp-for="@Model[i].Exist" type="checkbox" class="form-check-input" />
        <label asp-for="@Model[i].Exist" class="form-check-label">@Model[i].RoleName</label>

        <input asp-for="@Model[i].RoleName" type="hidden" />
        <input asp-for="@Model[i].RoleId" type="hidden" />
    </div>
    }

    <input class="btn btn-success" type="submit" value="Yetki Kaydet" />

</form>

MainProject/Views/Admin/RoleCreate.cshtml
@model MainProject.ViewModels.RoleViewModel

@{
    ViewData["Title"] = "RoleCreate";
    Layout = "~/Views/Admin/_AdminLayout.cshtml";
}

<h3>Rol Oluşturma</h3>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="RoleCreate">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>            
            <div class="form-group">
                <input type="submit" value="Rol Oluştur" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

MainProject/Views/Admin/RoleUpdate.cshtml
@model MainProject.ViewModels.RoleViewModel

@{
    ViewData["Title"] = "RoleUpdate";
    Layout = "~/Views/Admin/_AdminLayout.cshtml";
}



<h4>Rol Güncelleme</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="RoleUpdate">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />
          
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

MainProject/Views/Admin/Roles.cshtml
@model List<AppIdentityRole>
@{
    ViewData["Title"] = "Roles";
    Layout = "~/Views/Admin/_AdminLayout.cshtml";
}

<h3>Roller</h3>
<hr />

<table class="table table-bordered table-striped">
    <tr>
        <th>Id</th>
        <th>Rol İsmi</th>
        <th>Silme</th>
        <th>Güncelleme</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Id</td>
            <td>@item.Name</td>
            <td>
                <form  asp-action="RoleDelete" asp-route-id="@item.Id" method="post">
                    <button class="btn btn-warning" type="submit">Sil</button>
                </form>
            </td>
            <td><a class="btn btn-outline-primary" asp-action="RoleUpdate" asp-route-id="@item.Id">Güncelle</a></td>
        </tr>
    }
</table>
<a asp-action="RoleCreate" class="btn btn-outline-info float-sm-right">Role Oluştur</a>

MainProject/Views/Admin/Users.cshtml
@model List<AppIdentityUser>
@{
    ViewData["Title"] = "Users";
    Layout = "~/Views/Admin/_AdminLayout.cshtml";
}

<h3>Users</h3>

<hr />
<table class="table table-bordered table-striped ">
    <tr>
        <td>User Id</td>
        <td>User name</td>
        <td>Email</td>
        <td>Roller</td>
        <td>Rol Atama</td>

    </tr>
    @if (Model.Count() == 0)
    {
        <tr>
            <td colspan="3">Hiç üye yok!</td>
        </tr>

    }
    else
    {
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.UserName</td>
                <td>@item.Email</td>
                <td user-roles="@item.Id"></td>
                <td><a class="btn btn-success" asp-action="RoleAssign" asp-route-id="@item.Id">Yetkilendir</a></td>
            </tr>
        }
    }
</table>

MainProject/Views/Admin/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <script src="~/lib/jquery/jquery.js"></script>
    <link href="~/lib/twitter-bootstrap/css/bootstrap.css" rel="stylesheet" />
    <script src="~/lib/twitter-bootstrap/js/bootstrap.min.js"></script>
    <link href="~/css/Sidebar.css" rel="stylesheet" />
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand"asp-action="Index" asp-controller="Home">Home</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-link">
                        <a class="nav-link" asp-action="Index" asp-controller="Admin">Admin Sayfa <span class="sr-only">(current)</span></a>
                    </li>
                   
                </ul>
                
                    <ul class="navbar-nav">
                        <li class="nav-link">
                            <a class="nav-link" asp-action="Logout" asp-controller="Member" asp-route-returnUrl="/Home/">Çıkış <span class="sr-only">(current)</span></a>
                        </li>

                    </ul>
              
            </div>
        </div>
    </nav>

    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2 px-1 pt-4">
                <div class="sidebar">
                    <a class="btn btn-dark btn-block mt-2" asp-action="Users" asp-controller="Admin">Kullanıcılar</a>
                    <a class="btn btn-dark btn-block" asp-action="Roles" asp-controller="Admin">Roller</a>
                    <a class="btn btn-dark btn-block" asp-action="Claims" asp-controller="Admin">Claims</a>
                    <a class="btn btn-dark btn-block" asp-action="HomePagePhotos" asp-controller="Admin">Anasayfa İlan Resimleri</a>
                    <a class="btn btn-warning btn-block my-2" asp-action="Logout" asp-controller="Admin" asp-route-returnUrl="/Home/">Çıkış</a>
                </div>
            </div>
            <div class="col-md-10">
                @RenderBody()
            </div>           

        </div>
        
    </div>
</body>
</html>