core2/Entities/Employee.cs
using System.ComponentModel.DataAnnotations;

namespace core2.Entities
{
    public class Employee
    {
        [Key]
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int CityId { get; set; }
    }
}

core2/Controllers/EmployeeController.cs
using core2.Entities;
using core2.Model;
using core2.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

namespace core2.Controllers
{
    public class EmployeeController : Controller
    {
        private ICalculate _calculator;

        public EmployeeController(ICalculate calculator)
        {
            _calculator = calculator;
        }

        public IActionResult Add()
        {

            var employeeAddViewModel = new EmployeeAddViewModel
            {
                Employee = new Employee(),
                Cities = new List<SelectListItem>
                {
                   new SelectListItem{Text="Ankara",Value="6" },
                   new SelectListItem{Text="İstanbul",Value="34"}
                }
            };

            return View(employeeAddViewModel);
        }

        [HttpPost]
        public IActionResult Add(Employee employee)
        {

            return View();
        }
        public string Calculate()
        {

            return _calculator.Calculate(100).ToString();

        }
    }
}

core2/Views/Employee/Add.cshtml
@model core2.Model.EmployeeAddViewModel;


    <form asp-controller="Employee" asp-action="Add">
        <label asp-for="Employee.Id"></label> <input asp-for="Employee.Id" /><br />
        <label asp-for="Employee.FirstName"></label><input asp-for="Employee.FirstName" /><br />
        <label asp-for="Employee.LastName"></label> <input asp-for="Employee.LastName" /><br />
        City Id: <select asp-for="Employee.CityId" asp-items="Model.Cities"></select> <br />

        <button type="submit">Add</button>
    </form>

    <br /><br /><br />
    <employee-list count="4"></employee-list>


@section MySection{ 
    Some içerik
}